import Navbar from "@/components/Navbar";
import "./globals.css";
import { Ropa_Sans } from "next/font/google";
import Footer from "@/components/Footer";
import DownloadBtn from "@/components/DownloadBtn";

const ropaSans = Ropa_Sans({ subsets: ["latin"], weight: "400" });

export const metadata = {
  title: "Valopedia: Unofficial Valorant Wiki",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={ropaSans.className}>
        <Navbar />
        {children}
        <DownloadBtn />
        <Footer />
      </body>
    </html>
  );
}
